// COUNTRIES
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_DETAILS = "GET_DETAILS";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

// ACTIVITIES
export const GET_ACTIVITIES = "GET_ACTIVITIES";
