// COUNTRIES
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_DETAILS = "GET_DETAILS";
export const CLEAR_DETAILS = "CLEAR_DETAILS";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT";
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";
export const FILTER = "FILTER";
export const ORDER_ALPHABETICALLY = "ORDER_ALPHABETICALLY";
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";

// ACTIVITIES
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const GET_ACTIVITY_DETAILS = "GET_ACTIVITY_DETAILS";
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
